// export const PRODUCTLIST_ADD = 'PRODUCTLIST_ADD';
// export const PRODUCTLIST_LOAD = 'PRODUCTLIST_LOAD';

export const PRODUCT_REQUEST = 'PRODUCT_REQUEST';
export const PRODUCT_RECEIVED = 'PRODUCT_RECEIVED';
export const PRODUCT_ERROR = 'PRODUCT_ERROR';
