export const ARTICLELIST_LOAD = 'ARTICLELIST_LOAD'
export const ARTICLELIST_ADD = 'ARTICLELIST_ADD'
export const ARTICLELIST_INIT = 'ARTICLELIST_INIT'

export const ARTICLELIST_REQUEST = 'ARTICLELIST_REQUEST'
export const ARTICLELIST_RECEIVED = 'ARTICLELIST_RECEIVED'
export const ARTICLELIST_ERROR = 'ARTICLELIST_ERROR'