export const SUBSCRIBLELIST_REQUEST = 'SUBSCRIBLELIST_ARTICLE_REQUEST';
export const SUBSCRIBLELIST_RECEIVED = 'SUBSCRIBLELIST_ARTICLE_RECEIVED';
export const SUBSCRIBLELIST_ERROR = 'SUBSCRIBLELIST_ARTICLE_ERROR';
