export const SUBSCRIBLELIST_REQUEST = 'SUBSCRIBLELIST_SUBSCRIBETEACHER_REQUEST';
export const SUBSCRIBLELIST_RECEIVED = 'SUBSCRIBLELIST_SUBSCRIBETEACHER_RECEIVED';
export const SUBSCRIBLELIST_ERROR = 'SUBSCRIBLELIST_SUBSCRIBETEACHER_ERROR';
