export const USERINFO_LOAD = 'USERINFO_LOAD';
export const USERINFO_SCORE = 'USERINFO_SCORE';
export const USERINFO_NAME = 'USERINFO_NAME';
export const USERINFO_ACCOUNT = 'USERINFO_ACCOUNT';
export const USERINFO_ID = 'USERINFO_ID';

export const USERINFO_REQUEST = 'USERINFO_REQUEST';
export const USERINFO_RECEIVED = 'USERINFO_RECEIVED';
export const USERINFO_ERROR = 'USERINFO_ERROR';
export const USERBIND_GET_CODE = 'USERBIND_GET_CODE';
