export const USERINFO_REQUEST = 'USERINFO_REQUEST';
export const USERINFO_RECEIVED = 'USERINFO_RECEIVED';
export const USERINFO_ERROR = 'USERINFO_ERROR';
export const USERINFO_CHANGE = 'USERINFO_CHANGE';
