export const TEAM_CHANGE_ADD='TEAM_CHANGE_ADD';
export const TEAM_CHANGE_DEL='TEAM_CHANGE_DEL';
export const TEAM_CHANGE_IN8='TEAM_CHANGE_IN8';
export const TEAM_CHANGE_IN4='TEAM_CHANGE_IN4';
export const TEAM_CHANGE_IN2='TEAM_CHANGE_IN2';
export const TEAM_CHANGE_CHAMPION='TEAM_CHANGE_CHAMPION';
export const TEAM_ALL_OK='TEAM_ALL_OK';
